# Generated by Django 3.2.4 on 2021-06-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
